# Generated by Django 4.2.2 on 2024-12-06 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_alter_userprofile_company'),
        ('checkout', '0003_cart_payment_return'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo inicial')),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo final')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de apertura')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('carts', models.ManyToManyField(blank=True, related_name='cash_registers', to='checkout.cart')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to='users.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del movimiento')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='checkout.cart')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='cash_register.cashregister')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.paymentmethod', verbose_name='Método de pago')),
            ],
        ),
    ]
