# Generated by Django 4.2.2 on 2025-01-05 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_company'),
        ('cash_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmovement',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CashMovements', to='users.company'),
            preserve_default=False,
        ),
    ]
