# Generated by Django 5.1.6 on 2026-04-26 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0002_cashmovement_company'),
        ('checkout', '0010_remove_cart_cash_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Movement Date'),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.paymentmethod', verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closing Date'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='closing_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Closing Balance'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Opening Date'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Initial Balance'),
        ),
    ]
