# Generated by Django 4.2.2 on 2024-11-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='suppliers/receipts/', verbose_name='Remito'),
        ),
    ]
