# Generated by Django 4.2.2 on 2024-11-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
