# Generated by Django 4.2.2 on 2024-11-29 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_debt_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='accounts.person'),
        ),
    ]
