# Generated by Django 4.2.2 on 2024-12-01 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_company'),
        ('accounts', '0007_supplierentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_packs', to='users.company', verbose_name='Compañía')),
                ('entries', models.ManyToManyField(related_name='packs', to='accounts.supplierentry', verbose_name='Entradas')),
            ],
        ),
    ]
