# Generated by Django 4.2.2 on 2024-12-01 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_entrypack'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrypack',
            name='supplier',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='entry_packs', to='accounts.supplier', verbose_name='Proveedor'),
            preserve_default=False,
        ),
    ]
