# Generated by Django 4.2.2 on 2024-12-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_entrypack_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierentry',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
