# Generated by Django 5.1.6 on 2026-04-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_debt_company'),
        ('users', '0005_alter_company_options_alter_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI'),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('company', 'dni')},
        ),
    ]
