# Generated by Django 4.2.2 on 2024-12-03 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_paymentmethod_cart_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_return',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
