# Generated by Django 4.2.2 on 2024-12-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_cart_payment_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
