# Generated by Django 4.2.2 on 2024-12-11 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_cart_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartline',
            name='total',
        ),
        migrations.AddField(
            model_name='cartline',
            name='name',
            field=models.CharField(default='Inválido', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartline',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
    ]
