# Generated by Django 4.2.2 on 2024-12-11 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_item_hide_alter_item_cost'),
        ('checkout', '0005_remove_cartline_total_cartline_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartline',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_lines', to='inventory.item'),
        ),
    ]
