# Generated by Django 4.2.2 on 2025-01-01 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_company'),
        ('checkout', '0006_alter_cartline_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartline',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carts_lines', to='users.company'),
            preserve_default=False,
        ),
    ]
