# Generated by Django 5.1.6 on 2025-03-05 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0002_cashmovement_company'),
        ('checkout', '0008_cart_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cash_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asigned_carts', to='cash_register.cashregister'),
        ),
    ]
