# Generated by Django 5.1.6 on 2025-03-05 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_cart_cash_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cash_register',
        ),
    ]
