# Generated by Django 4.2.2 on 2024-11-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stockable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(blank='True', related_name='items', to='inventory.category'),
        ),
    ]
