# Generated by Django 4.2.2 on 2024-12-11 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_item_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hide',
            field=models.BooleanField(default=False, help_text='Ocultar el ítem en listas y búsquedas'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo que el proveedor cobra por el artículo', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
