# Generated by Django 4.2.2 on 2025-01-12 02:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_debt_company'),
        ('users', '0003_alter_userprofile_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='users.company')),
            ],
        ),
        migrations.CreateModel(
            name='UsageSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.DurationField(help_text='Duración en formato de tiempo (ej.: 2 horas)')),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_sessions', to='accounts.person')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_sessions', to='users.company')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_sessions', to='cyber_control.device')),
            ],
        ),
    ]
