# Generated by Django 4.2.2 on 2025-01-13 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagesession',
            name='total_duration',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Duración total acumulada'),
        ),
    ]
