# Generated by Django 4.2.2 on 2025-01-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_control', '0002_usagesession_total_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagesession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
