# Generated by Django 5.1.6 on 2026-04-26 01:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_control', '0003_usagesession_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagesession',
            name='duration',
            field=models.DurationField(help_text='Duration in time format (e.g., 2 hours)'),
        ),
        migrations.AlterField(
            model_name='usagesession',
            name='total_duration',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Accumulated total duration'),
        ),
    ]
