# Generated by Django 5.1.6 on 2026-04-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_wiki', '0002_wikicategory_wikientry_delete_wikipage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikicategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
