# Generated by Django 4.2.2 on 2024-12-29 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_userprofile_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_supplierentry_cost_supplierentry_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255, verbose_name='Artículo')),
                ('item_details', models.TextField(blank=True, null=True, verbose_name='Detalles del artículo')),
                ('reception_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de recepción')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Proceso'), ('completed', 'Finalizado')], default='pending', max_length=50, verbose_name='Estado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='users.company')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='accounts.person', verbose_name='Persona')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
            ],
        ),
        migrations.CreateModel(
            name='ReceptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptionLogs', to='users.company')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='receptions.reception', verbose_name='Recepción')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
