# Generated by Django 4.2.2 on 2024-12-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='auth_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Autenticidad'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Entregado')], default='pending', max_length=50, verbose_name='Estado'),
        ),
    ]
