# Generated by Django 5.1.6 on 2026-04-26 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_person_dni_alter_person_unique_together'),
        ('receptions', '0002_reception_auth_code_alter_reception_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='auth_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Authentication code'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='item',
            field=models.CharField(max_length=255, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='item_details',
            field=models.TextField(blank=True, null=True, verbose_name='Item details'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='accounts.person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Received by'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='reception_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Reception date'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=50, verbose_name='Status'),
        ),
    ]
