# Generated by Django 5.1.6 on 2026-04-26 01:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_logs', '0002_alter_actionlog_company'),
        ('users', '0005_alter_company_options_alter_company_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Creación'), ('EDIT', 'Edición'), ('DELETE', 'Eliminación')], help_text='Tipo de acción realizada.', max_length=10),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Empresa asociada a la acción (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='users.company'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='details',
            field=models.TextField(help_text='Descripción detallada de los datos afectados (antes/después).'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='model_name',
            field=models.CharField(help_text='Nombre del modelo donde se realizó la acción.', max_length=255),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='object_id',
            field=models.PositiveIntegerField(help_text='ID del objeto afectado.'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la acción.'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la acción.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
